shouldLogCapabilityStatement: true

users:
  - name: Sina HÃ¼llmann
    kvnr: X110609524
    useVirtualEgk: false
    remoteFdV: DUMMY VALUE
  - name: Alice
    kvnr: X110645443
    useVirtualEgk: false
    remoteFdV: RU-mock-LTU_RU

remote-fdv:
  - name: mock-local
    url: https://localhost:443
    version: 1.0.1
    accessKey: apiKey2024
  - name: RU-mock-LTU_RU
    url: https://erp-remote-fdv.dev.gematik.solutions
    version: 1.0.1
    accessKey: apiKey2024
  - name: RU-DEV-mock-LTU_RU
    url: https://erp-remote-fdv.ru-dev.gematik.solutions
    version: 1.0.1
    accessKey: apiKey2024
